import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import DashboardNavbar from "../_components/DashboardNavbar";
import { IconType } from "react-icons";
import { FiHome, FiSettings, FiHelpCircle } from "react-icons/fi";
import { GrTemplate } from "react-icons/gr";
import { SiPurescript } from "react-icons/si";
import { RiOpenaiFill } from "react-icons/ri";
import ThemeSwitcher from "../_components/ThemeSwitcher";

export const metadata: Metadata = {
  title: "ViralScript",
  description: "Generated by create next app",
};

interface NavItem {
  name: string;
  href: string;
  icon: IconType;
}

const navItems: NavItem[] = [
  { name: "Dashboard", href: "/dashboard", icon: FiHome },
  {
    name: "AI Script Generator",
    href: "/dashboard/ai-script-generator",
    icon: RiOpenaiFill,
  },
  { name: "My Scripts", href: "/dashboard/my-scripts", icon: SiPurescript },
  { name: "Templates", href: "/dashboard/templates", icon: GrTemplate },
  { name: "Settings", href: "/dashboard/settings", icon: FiSettings },
  { name: "Help Center", href: "/dashboard/helps", icon: FiHelpCircle },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <DashboardNavbar />
      <div className="drawer md:drawer-open">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content flex flex-col">{children}</div>

        <div className="drawer-side h-[1000px] md:h-screen">
          <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
          <aside className="w-80 h-full bg-[#ffffff]/95 dark:bg-[#1a1a1a]/95 border-[#e5e7eb] dark:border-[#2a2a2a] border-r ">
            <nav className="flex flex-col px-2 md:pt-3">
              {navItems.map((item) => (
                <Link
                  key={item.name}
                  href={item.href}
                  className="flex items-center py-3 nav-link text-[#171717] dark:text-[#ededed] hover:text-[#ff3898] px-4  rounded-lg transition-all duration-300 hover:bg-[#f3f4f6] dark:hover:bg-[#2a2a2a] cursor-pointer font-medium"
                >
                  <item.icon className="w-5 h-5 mr-3" />
                  <span className="font-medium">{item.name}</span>
                </Link>
              ))}

              <div className="flex md:hidden items-center py-3  px-3  rounded-lg transition-all duration-300  cursor-pointer font-medium">
                <ThemeSwitcher />
              </div>
            </nav>
          </aside>
        </div>
      </div>
    </main>
  );
}
